### ISSUE TITLE
Invalid certificate in workmen.biojs.net

### ISSUE THREAD

**Issue by homonecloco** [biojs/sniper#7]
Hi, 
I don´t know if this is the right place to report it, but looking at my component in http://workmen.biojs.net/demo/biojs-vis-sam/simple does´t load the example, as I get the following errors:

```
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “wzrd.in” which could put your confidential information at risk. (biojs-vis-sam@0.1.6, line 0)
[Error] ReferenceError: Can't find variable: require
	global code (simple, line 16)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “wzrd.in” which could put your confidential information at risk. (biojs-io-sam@latest, line 0)
```
Is there anything I can do to fix this?
Best, 
Ricardo.

**Comment by greenify** [comment]
> I don´t know if this is the right place to report it

Yes this is the wrong repo - in dubito pro biojs/biojs ;-)

Browserify-cdn uses a Comodo certificate which should be supported by any modern browser.
Are other widgets working for you?

This would be correct issue to report your problem to:

https://github.com/jfhbrook/browserify-cdn/issues/78
